sudo: required
language: generic

services:
 - docker
 
before_install:
 - docker build -t achaigne/react-test -f ./client/Dockerfile.dev ./client
 
script:
 - docker run -e CI=true achaigne/react-test npm test

after_success:
 - docker build -t xecius/multi-client ./client
 - docker build -t xecius/multi-nginx ./nginx
 - docker build -t xecius/multi-server ./server
 - docker build -t xecius/multi-worker ./worker
 # login 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # push to docker hub 
 - docker push xecius/multi-client
 - docker push xecius/multi-nginx 
 - docker push xecius/multi-server
 - docker push xecius/multi-worker
 
deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-193606548371'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
